### ISSUE TITLE
poster

### ISSUE THREAD

**Issue by farwarx** [Afterster/videojs-vlc#1]
Hi,
When a poster is set in <video>, it stay on movie when playing.
If we pass in fullscreen, it disappear.
But if we return in web page, poster is display on the movie.

<video id="test" class="video-js vjs-default-skin" controls preload="none" poster="poster.jpg" data-setup='{"techOrder": ["html5", "flash", "vlc"] }>

**Comment by Afterster** [comment]
I was missing two method implementation. Fixed now, thanks for the report!

**Comment by farwarx** [comment]
thanks :)
