### ISSUE TITLE
videojs.util is undefined

### ISSUE THREAD

**Issue by ewoo-ap** [Afterster/videojs-vlc#4]
More of an inquiry than an issue; I'm fairly new to web dev & Video.js

I'm trying to get the example.html up & running, but all that's displayed is a black rectangle and the `<video>...</video>` tag being rendered as `<div style="width: 600px; height: 300px;" class="video-js vjs-default-skin vjs-paused" id="video"></div>`.

The only lines I've modified in example.html is to point to the Video.js CDN hosted script/css and my local videojs-vlc.js. I'm using Firefox 32.

**The console output is:**
_Specified "type" attribute of "video/mp4" is not supported. Load of media resource http://video-js.zencoder.com/oceans-clip.mp4 failed._
_All candidate resources failed to load. Media load paused._
_TypeError: videojs.util is undefined_ (videojs-vlc.js, line 14)

Am I missing something obvious? Thanks in advance.

![videojs vlc plugin troubleshoot](https://cloud.githubusercontent.com/assets/1766531/7710685/7946b0ea-fe33-11e4-897c-85a26acf29b3.png)

**Comment by Afterster** [comment]
I think you are missing something obvious yes :)
- You must have VLC Web Plug-in installed on your browser
- You should build the project with **grunt** to use the example.html file directly
