### ISSUE TITLE
No compatible source was found on this video

### ISSUE THREAD

**Issue by nitmir** [Afterster/videojs-vlc#7]
Hello
I'm using firefox 38.1.0 with vlc 2.2.0 (web plugin working with and <embed> tag), on commit 99d4c0d850e0e45750075df59361ffc7a387a285 (current HEAD)
I have successfully ran npm install and grunt without error, but my video do not load.
Example url: https://power.genua.fr/static/videojs/vlc/example.html

Am i missing something ?
Edit:
The video play well using html5 https://power.genua.fr/static/videojs/vlc/example2.html

**Comment by nitmir** [comment]
found the issue, my navigator do not provide the list of available plugins the javascript so videojs.Vlc.isSupported return always false.
-_-'

Adding :

```
vlc =  document.createElement('embed');
vlc.setAttribute('style', 'width:0px; height:0px;');
vlc.setAttribute('type', 'application/x-vlc-plugin');
vlc.setAttribute('id','test_vlc');
document.body.appendChild(vlc)
if(typeof vlc.playlist != 'undefined'){
    return true;
}
vlc.parentNode.removeChild(element);
```

fix my issue.

**Comment by Afterster** [comment]
That's an interesting fix. I encountered myself the problem and didn't found a good way to fix it.
So thanks a lot for this pr!
